// Generated by CoffeeScript 1.6.3
(function() {
  Leap.pipeline('interactable_coordinates', function() {
    var selector;
    selector = 'a';
    return {
      global: true,
      onFrame: function(frame) {
        return frame.interactableCoordinates = $(selector).absolutePositions();
      }
    };
  });

  $.fn.absolutePositions = function() {
    var left, out, top;
    top = $(window).scrollTop();
    left = $(window).scrollLeft();
    out = [];
    this.each(function(i, el) {
      var offset;
      el = $(el);
      offset = el.offset();
      return out.push([offset.top - top, offset.left - left, offset.top - top + el.height(), offset.left - left + el.width()]);
    });
    return out;
  };

}).call(this);
