// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("TemplateInspector", []);

  app.controller("Leap", [
    "$scope", "LeapController", "Template", "Menu", "$rootScope", '$compile', function($scope, LeapController, Template, Menu, $rootScope, $compile) {
      $scope.heightOffset = 0;
      $scope.working = false;
      $scope.hud = true;
      $scope.hand_elements = {};
      Menu.initialize();
      $scope.keypress = function(event) {
        switch (event.keyCode) {
          case 's'.charCodeAt(0):
          case 'p'.charCodeAt(0):
            LeapController.paused = !LeapController.paused;
            return $rootScope.$broadcast('paused', LeapController.paused);
          case 'h'.charCodeAt(0):
            $scope.hud = !$scope.hud;
            return $rootScope.$broadcast('hud', $scope.hud);
        }
      };
      LeapController.on('foundHand', function(id) {
        console.log('found hand', id);
        $scope.hand_elements[id] = angular.element("<div data-hand='" + id + "' class='hand'></div>");
        angular.element(document.body).append($scope.hand_elements[id]);
        return $compile($scope.hand_elements[id])($scope);
      });
      LeapController.on('lostHand', function(id) {
        console.log('lost hand', id);
        return $scope.hand_elements[id].remove();
      });
      LeapController.on("frame", function(frame) {
        if (LeapController.paused) {
          return;
        }
        if ($scope.working) {
          console.log("dropping frame");
          return;
        }
        $scope.working = true;
        $scope.hands = frame.hands;
        $scope.$digest();
        return $scope.working = false;
      });
      return LeapController.on('handClose', function(event) {});
    }
  ]);

}).call(this);
