// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("TemplateInspector", []);

  app.controller("LeapController", [
    "$scope", "Leap", "$rootScope", '$compile', function($scope, Leap, $rootScope, $compile) {
      $scope.heightOffset = 0;
      $scope.working = false;
      $scope.hud = true;
      $scope.hand_elements = {};
      $scope.keypress = function(event) {
        switch (event.keyCode) {
          case 's'.charCodeAt(0):
          case 'p'.charCodeAt(0):
            Leap.paused = !Leap.paused;
            return $rootScope.$broadcast('paused', Leap.paused);
          case 'h'.charCodeAt(0):
            $scope.hud = !$scope.hud;
            return $rootScope.$broadcast('hud', $scope.hud);
        }
      };
      Leap.on('foundHand', function(id) {
        console.log('found hand');
        $scope.hand_elements[id] = angular.element("<div data-hand='" + id + "' class='hand'></div>");
        angular.element(document.body).append($scope.hand_elements[id]);
        return $compile($scope.hand_elements[id])($scope);
      });
      Leap.on('lostHand', function(id) {
        console.log('lost hand');
        return $scope.hand_elements[id].remove();
      });
      Leap.on("frame", function() {
        if (Leap.paused) {
          return;
        }
        if ($scope.working) {
          console.log("dropping frame");
          return;
        }
        $scope.working = true;
        $scope.$digest();
        return $scope.working = false;
      });
      $scope.$on('open', function(scope, data) {
        return console.log('open', data);
      });
      return $scope.$on('close', function(scope, data) {
        return console.log('close', data);
      });
    }
  ]);

}).call(this);
