// Generated by CoffeeScript 1.6.3
(function() {
  app.factory("LeapController", [
    function() {
      var controller;
      console.log("connecting");
      controller = new Leap.Controller();
      controller.on("connect", function() {
        return console.log("Successfully connected.");
      });
      controller.on("deviceDisconnected", function() {
        return console.log("A Leap device has been disconnected.");
      });
      controller.use('hand_position', {
        positioning: 'absolute',
        "if": function(hand) {
          return hand.side === 'left';
        }
      });
      controller.use('hand_position', {
        positioning: {
          CDGain: 14
        },
        "if": function(hand) {
          return hand.side === 'right';
        }
      });
      controller.connect();
      return controller;
    }
  ]);

}).call(this);
