// Generated by CoffeeScript 1.6.3
(function() {
  app.factory("Leap", [
    function() {
      var controller, previousValidHandIds;
      console.log("connecting");
      controller = new Leap.Controller();
      controller.on("connect", function() {
        return console.log("Successfully connected.");
      });
      controller.on("deviceDisconnected", function() {
        return console.log("A Leap device has been disconnected.");
      });
      previousValidHandIds = [];
      controller.on("frame", function() {
        var id, newValidHandIds, _i, _j, _len, _len1, _results;
        newValidHandIds = controller.lastValidFrame.hands.map(function(hand) {
          return hand.id;
        });
        for (_i = 0, _len = previousValidHandIds.length; _i < _len; _i++) {
          id = previousValidHandIds[_i];
          if (!newValidHandIds.includes(id)) {
            previousValidHandIds.remove(id);
            controller.emit('lostHand', id);
          }
        }
        _results = [];
        for (_j = 0, _len1 = newValidHandIds.length; _j < _len1; _j++) {
          id = newValidHandIds[_j];
          if (!previousValidHandIds.includes(id)) {
            previousValidHandIds.push(id);
            _results.push(controller.emit('foundHand', id));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
      controller.connect();
      return controller;
    }
  ]);

}).call(this);
