// Generated by CoffeeScript 1.6.3
(function() {
  app.factory('Template', [
    function() {
      var object;
      object = {
        template_for: function(target) {
          var encompassing_templates, node, parent, _i, _len, _ref;
          encompassing_templates = [];
          node = void 0;
          parent = void 0;
          while (true) {
            parent = target.parentNode;
            if (!parent) {
              return false;
            }
            _ref = parent.childNodes;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              node = _ref[_i];
              if (node.substringData) {
                if (node.substringData(0, 13) === "begin partial") {
                  encompassing_templates.push(node);
                } else if (node.substringData(0, 11) === "end partial") {
                  encompassing_templates.pop();
                }
              } else if (node === target) {
                if (encompassing_templates.length) {
                  return encompassing_templates.pop().substringData(14, 256);
                } else {
                  target = parent;
                  break;
                }
              }
            }
          }
        },
        open: function(element) {
          var path;
          if (path = object.template_for(element)) {
            console.log('setting location', "x-mine://open?file=" + path);
            window.location.assign("x-mine://open?file=" + path);
            return window.location.assign("#");
          }
        }
      };
      return object;
    }
  ]);

}).call(this);
