// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("TemplateInspector", []);

  app.controller("LeapController", [
    "$scope", "Leap", "$rootScope", function($scope, Leap, $rootScope) {
      $scope.hands = [];
      $scope.heightOffset = 0;
      $scope.paused = false;
      $scope.working = false;
      $scope.hud = true;
      $scope.keypress = function(event) {
        switch (event.keyCode) {
          case 's'.charCodeAt(0):
          case 'p'.charCodeAt(0):
            Leap.paused = !Leap.paused;
            $rootScope.$broadcast('paused', Leap.paused);
            break;
          case 'h'.charCodeAt(0):
            $scope.hud = !$scope.hud;
            $rootScope.$broadcast('hud', $scope.hud);
        }
        return $scope.style = function() {
          return console.log('style controller called');
        };
      };
      return Leap.on("frame", function() {
        if (Leap.paused) {
          return;
        }
        if ($scope.working) {
          console.log("dropping frame");
          return;
        }
        $scope.working = true;
        $scope.hands = Leap.lastValidFrame.hands;
        $scope.$digest();
        return $scope.working = false;
      });
    }
  ]);

}).call(this);
