// Generated by CoffeeScript 1.6.3
(function() {
  Array.prototype.includes = function(item) {
    return this.indexOf(item) >= 0;
  };

  Array.prototype.getById = function(id) {
    var item, _i, _len;
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      item = this[_i];
      if (item.id === id) {
        return item;
      }
    }
  };

}).call(this);
