// Generated by CoffeeScript 1.6.3
(function() {
  app.directive('hand', [
    'Leap', function(Leap) {
      return {
        restrict: 'A',
        link: function(scope, elem, attrs) {
          return scope.$watch('hands', function(newHands, oldHands) {
            if (scope.hand = newHands[0]) {
              elem[0].style.left = (document.body.offsetWidth / 2) + (scope.hand.palmPosition[0] * 8) + "px";
              return elem[0].style.top = (document.body.offsetHeight / 2) + ((scope.hand.palmPosition[1] - 150) * -8) + "px";
            }
          });
        }
      };
    }
  ]);

}).call(this);
