// Generated by CoffeeScript 1.6.3
(function() {
  Leap.service('hand_entry_events', function() {
    var previousValidHandIds;
    previousValidHandIds = [];
    return {
      frame: function(frame) {
        var id, newValidHandIds, _i, _j, _len, _len1, _results;
        newValidHandIds = frame.hands.map(function(hand) {
          return hand.id;
        });
        for (_i = 0, _len = previousValidHandIds.length; _i < _len; _i++) {
          id = previousValidHandIds[_i];
          if (!newValidHandIds.includes(id)) {
            previousValidHandIds.remove(id);
            this.emit('lostHand', id);
          }
        }
        _results = [];
        for (_j = 0, _len1 = newValidHandIds.length; _j < _len1; _j++) {
          id = newValidHandIds[_j];
          if (!previousValidHandIds.includes(id)) {
            previousValidHandIds.push(id);
            _results.push(this.emit('foundHand', id));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  });

}).call(this);
