// Generated by CoffeeScript 1.6.3
(function() {
  Leap.service('hand_open', function(options) {
    var extra_hand_data, openGestureContants;
    options || (options = {});
    openGestureContants = {
      tips_at: options.tips_at || 0.6,
      minTip: options.minTip || 0.3,
      maxTip: options.maxTip || 1.3
    };
    extra_hand_data = [];
    return {
      hand: function(hand) {
        var new_open_percent, _name;
        extra_hand_data[_name = hand.id] || (extra_hand_data[_name] = {});
        new_open_percent = Math.round((Math.abs(hand.roll()) - openGestureContants.minTip) / (openGestureContants.maxTip - openGestureContants.minTip) * 100);
        if (new_open_percent !== extra_hand_data[hand.id].old_open_percent) {
          extra_hand_data[hand.id].old_open_percent = new_open_percent;
          this.emit('handOpenPercent', hand.id, new_open_percent);
          if (extra_hand_data[hand.id].open && new_open_percent < openGestureContants.tips_at) {
            extra_hand_data[hand.id].open = false;
            this.emit('handClose', hand.id);
          }
          if (!extra_hand_data[hand.id].open && new_open_percent >= openGestureContants.tips_at) {
            extra_hand_data[hand.id].open = true;
            return this.emit('handOpen', hand.id);
          }
        }
      }
    };
  });

}).call(this);
