// Generated by CoffeeScript 1.6.3
(function() {
  Leap.service('hand_position', function(options) {
    var position_methods, positioning;
    positioning = options.positioning || 'absolute';
    position_methods = {
      absolute: function(hand) {
        var scale, vertical_offset;
        scale = 8;
        vertical_offset = -150;
        return {
          x: (document.body.offsetWidth / 2) + (hand.palmPosition[0] * scale),
          y: (document.body.offsetHeight / 2) + ((hand.palmPosition[1] + vertical_offset) * scale * -1)
        };
      }
    };
    return {
      hand: function(hand) {
        return hand.screenPosition = angular.isFunction(positioning) ? positioning(hand) : position_methods[positioning](hand);
      }
    };
  });

}).call(this);
