// Generated by CoffeeScript 1.6.3
(function() {
  Leap.service('hand_side', function() {
    return {
      hand: function(hand) {
        return hand.side = 'left';
      }
    };
  });

}).call(this);
